use crate::engine::{extractor::FileFeatures, glossary::Glossary, Linker, MathEngine, Mapper};
use std::collections::HashMap;
use serde_json::json;

pub struct WikiProxy;

impl WikiProxy {
    /// Generates a beautiful Agent-Native Wiki page in Markdown for a single file.
    pub fn generate_markdown(
        target_path: &str,
        features: &FileFeatures,
        glossary: &Glossary,
    ) -> String {
        let mut wiki = String::new();
        let title = glossary.aliases.get(target_path).unwrap_or(&target_path.to_string()).clone();

        wiki.push_str(&format!("# 📄 {} \n\n", title));
        wiki.push_str(&format!("**物理路徑**: `{}`\n\n", target_path));
        wiki.push_str(&format!("**架構角色**: `{}`\n\n", if features.symbol_count > 10 { "核心樞紐 (HUB)" } else { "葉片節點 (LEAF)" }));
        
        wiki.push_str("### 🛠️ 語義特徵張量\n");
        wiki.push_str(&format!("*   **邏輯複雜度**: [{}{}] ({:.2})\n", 
            "█".repeat((features.control_flow_score * 5.0) as usize),
            "░".repeat(5 - (features.control_flow_score * 5.0).min(5.0) as usize),
            features.control_flow_score
        ));

        wiki.push_str("\n### 🔗 物理符號與出口 (SCIP Exports)\n");
        for sym in &features.exports {
            let sym_alias = glossary.aliases.get(&sym.id).unwrap_or(&sym.name);
            wiki.push_str(&format!("*   `{}` (L{})\n", sym_alias, sym.line));
        }
        
        wiki.push_str("\n---\n*Generated by CCAP Reverse Proxy | Local Fidelity Verified*");
        wiki
    }

    /// Chapter 15: Generates a high-entropy prompt for AI to enrich semantic descriptions.
    pub fn generate_ai_enrich_prompt(target_path: &str, features: &FileFeatures) -> String {
        let telegram = Mapper::to_telegram(target_path, features);
        format!(r#"
[CCAP AEP ENRICHMENT REQUEST]
TARGET: {}
TELEGRAM: {}

TASK: Based purely on the tags above, write a professional 100-word functional summary.
"#, target_path, telegram)
    }

    /// Chapter 15.2: Packages the entire project's AAAK data for global synthesis.
    pub fn generate_global_ai_package(results: &[(String, FileFeatures)]) -> String {
        let mut package = String::from("[CCAP GLOBAL STRATEGIC SYNTHESIS PACKAGE]\n");
        for (path, feat) in results {
            let telegram = Mapper::to_telegram(path, feat);
            package.push_str(&format!("{}\n", telegram));
        }
        package
    }

    /// Generates a project-level index with Dynamic Drill-down Graph.
    pub fn generate_project_index(
        repo_root: &str,
        results: &[(String, FileFeatures)],
        linker: &Linker,
        glossary: &Glossary,
    ) -> String {
        let mut wiki = String::new();
        let project_name = std::path::Path::new(repo_root).file_name().unwrap_or_default().to_string_lossy().to_string();
        
        wiki.push_str(&format!("# 🌌 專案戰略地圖：{} \n\n", project_name));
        wiki.push_str(&format!("**總掃描檔案數**: `{}`\n\n", results.len()));
        
        // Chapter 15.2: Load and Display "Project Soul" if it exists
        let soul_path = std::path::Path::new(repo_root).join(".ccap").join("project_soul.st");
        if soul_path.exists() {
            if let Ok(soul) = std::fs::read_to_string(soul_path) {
                wiki.push_str("### 🎭 專案靈魂故事 (AI Project Soul)\n");
                wiki.push_str(&format!("> {}\\n\\n", soul.trim()));
            }
        } else {
            wiki.push_str("*(提示: 執行 `wiki --ai-enrich-all` 以獲取 AI 產出的全局架構故事)*\\n\\n");
        }

        let edges = linker.export_edges();
        let paths = linker.get_node_paths();
        let mut sym_data = HashMap::new();
        for (path, features) in results {
            sym_data.insert(path.clone(), features.top_symbols.clone());
        }

        let k_rooms = 3.max(results.len() / 50).min(10);
        let clusters = MathEngine::spectral_cluster(&paths, &edges, k_rooms, &sym_data).unwrap_or_default();

        let mut rooms_json = Vec::new();
        for (i, cluster) in clusters.iter().enumerate() {
            if cluster.members.is_empty() { continue; }
            
            let mut kw_count: HashMap<String, usize> = HashMap::new();
            for m in &cluster.members {
                if let Some(syms) = sym_data.get(m) {
                    for s in syms { *kw_count.entry(s.to_lowercase()).or_insert(0) += 1; }
                }
            }
            let mut skw: Vec<_> = kw_count.into_iter().collect();
            skw.sort_by(|a, b| b.1.cmp(&a.1));

            let m_data: Vec<_> = cluster.members.iter().map(|m| {
                let feat = results.iter().find(|(p, _)| p == m).map(|x| &x.1);
                let alias = glossary.aliases.get(m).cloned().unwrap_or(m.clone());
                json!({
                    "path": m,
                    "label": alias,
                    "is_hub": feat.map_or(false, |f| f.symbol_count > 10),
                    "complexity": feat.map_or(0.0, |f| f.control_flow_score)
                })
            }).collect();

            rooms_json.push(json!({
                "id": i,
                "label": cluster.name,
                "value": cluster.members.len(),
                "keywords": skw.iter().take(8).map(|x| x.0.clone()).collect::<Vec<_>>(),
                "members": m_data
            }));
        }

        wiki.push_str("### 🏗️ 互動式戰略導航 (Click a Room to Enter)\n");
        wiki.push_str("<div style='position: relative;'>\n");
        wiki.push_str("  <button id='backBtn' style='display:none; position: absolute; top: 10px; left: 10px; z-index: 100; padding: 8px 16px; background: #AEB98F; color: white; border: none; border-radius: 4px; cursor: pointer;'>← 返回總覽</button>\n");
        wiki.push_str("  <div id='mynetwork' style='height: 600px; border: 2px solid #AEB98F; background-color: #ffffff; border-radius: 12px; margin-bottom: 30px;'></div>\n");
        wiki.push_str("</div>\n\n");

        let graph_data_json = json!({ "rooms": rooms_json }).to_string();
        wiki.push_str(&format!("@ROOM_DATA@{}@ROOM_DATA@\n", graph_data_json));

        wiki.push_str("### 🏢 語義能力摘要 (Capability Highlights)\n\n");
        for r in &rooms_json {
            let r_id = r["id"].as_u64().unwrap();
            wiki.push_str(&format!("#### 📦 {}\\n", r["label"]));
            
            let rs_path = std::path::Path::new(repo_root).join(".ccap").join(format!("room_soul_{}.st", r_id));
            if rs_path.exists() {
                if let Ok(s) = std::fs::read_to_string(rs_path) {
                    wiki.push_str(&format!("> **AI 語義昇華**: {}\\n\\n", s.trim()));
                }
            }

            let kw = r["keywords"].as_array().unwrap().iter().map(|v| v.as_str().unwrap()).collect::<Vec<_>>().join(" | ");
            wiki.push_str(&format!("* **核心語義**: `{}`\\n\\n", kw));
        }
        wiki
    }

    fn parse_inline_markdown(text: &str) -> String {
        let mut html = text.to_string();
        while let Some(start) = html.find('`') {
            if let Some(end) = html[start + 1..].find('`') {
                let end_idx = start + 1 + end;
                html = format!("{}<code>{}</code>{}", &html[..start], &html[start+1..end_idx], &html[end_idx+1..]);
            } else { break; }
        }
        while let Some(start) = html.find("**") {
            if let Some(end) = html[start + 2..].find("**") {
                let end_idx = start + 2 + end;
                html = format!("{}<strong>{}</strong>{}", &html[..start], &html[start+2..end_idx], &html[end_idx+2..]);
            } else { break; }
        }
        html
    }

    pub fn generate_html(markdown_content: &str) -> String {
        let mut wiki_html = String::new();
        let mut room_data = String::from("{}");

        for line in markdown_content.lines() {
            let trimmed = line.trim();
            if trimmed.is_empty() { continue; }
            if trimmed.starts_with("@ROOM_DATA@") {
                room_data = trimmed.replace("@ROOM_DATA@", "");
                continue;
            }
            if trimmed.starts_with("<div") || trimmed.starts_with("<button") { wiki_html.push_str(trimmed); continue; }
            if trimmed.starts_with("# ") { wiki_html.push_str(&format!("<h1>{}</h1>", Self::parse_inline_markdown(&trimmed[2..]))); }
            else if trimmed.starts_with("### ") { wiki_html.push_str(&format!("<h3>{}</h3>", Self::parse_inline_markdown(&trimmed[4..]))); }
            else if trimmed.starts_with("#### ") { wiki_html.push_str(&format!("<h4>{}</h4>", Self::parse_inline_markdown(&trimmed[5..]))); }
            else if trimmed.starts_with("* ") { wiki_html.push_str(&format!("<li>{}</li>", Self::parse_inline_markdown(&trimmed[2..]))); }
            else { wiki_html.push_str(&format!("<p>{}</p>", Self::parse_inline_markdown(trimmed))); }
        }

        format!(r#"
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>CCAP Strategic Mesh</title>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/vis-network/9.1.9/standalone/umd/vis-network.min.js"></script>
    <style>
        body {{ font-family: 'Segoe UI', system-ui, sans-serif; background-color: #f4f7f6; color: #2d3436; padding: 20px; }}
        #content {{ background: white; padding: 40px; border-radius: 20px; box-shadow: 0 15px 50px rgba(0,0,0,0.05); max-width: 1200px; margin: auto; border-top: 12px solid #AEB98F; }}
        h1 {{ font-size: 2.5em; color: #1e272e; margin-bottom: 30px; text-align: center; }}
        h3 {{ margin-top: 40px; color: #2c3e50; border-left: 5px solid #AEB98F; padding-left: 15px; }}
        h4 {{ color: #AEB98F; margin-top: 20px; }}
        code {{ background: #f1f2f6; padding: 2px 6px; border-radius: 4px; font-family: monospace; color: #d63384; font-weight: bold; }}
        .footer {{ text-align: center; margin-top: 50px; color: #b2bec3; font-size: 0.8em; }}
    </style>
</head>
<body>
    <div id="content">{}</div>
    <div class="footer">CCAP V6.0 Gold | The Hierarchical Semantic Mesh</div>
    <script type="text/javascript">
        const fullData = {};
        const container = document.getElementById('mynetwork');
        const backBtn = document.getElementById('backBtn');
        let network = null;

        function showMacroView() {{
            backBtn.style.display = 'none';
            const nodes = new vis.DataSet(fullData.rooms.map(r => ({{
                id: r.id,
                label: r.label + "\n(" + r.value + " files)",
                shape: 'dot',
                size: Math.sqrt(r.value) * 15,
                color: '#AEB98F',
                font: {{ size: 16, weight: 'bold' }},
                type: 'room'
            }})));
            const edges = new vis.DataSet([]);
            render(nodes, edges);
        }}

        function showMicroView(roomId) {{
            const room = fullData.rooms.find(r => r.id === roomId);
            if (!room) return;
            backBtn.style.display = 'block';
            const nodes = new vis.DataSet(room.members.map((m, idx) => ({{
                id: idx,
                label: m.label,
                shape: 'dot',
                size: m.is_hub ? 20 : 10,
                color: m.is_hub ? '#AEB98F' : '#D3D3D3',
                font: {{ size: 12 }},
                type: 'file'
            }})));
            const edges = new vis.DataSet([]); // Local bonds could be added here
            render(nodes, edges);
        }}

        function render(nodes, edges) {{
            const options = {{
                physics: {{ stabilization: true, barnesHut: {{ gravitationalConstant: -2000 }} }},
                interaction: {{ zoomView: true, dragView: true }}
            }};
            if (network) network.destroy();
            network = new vis.Network(container, {{ nodes, edges }}, options);
            network.on("click", function (params) {{
                if (params.nodes.length > 0) {{
                    const nodeId = params.nodes[0];
                    const node = nodes.get(nodeId);
                    if (node.type === 'room') {{
                        showMicroView(nodeId);
                    }}
                }}
            }});
        }}

        backBtn.onclick = showMacroView;
        showMacroView();
    </script>
</body>
</html>
        "#, wiki_html, room_data)
    }
}
