use crate::engine::{extractor::FileFeatures, glossary::Glossary, Linker, MathEngine};
use std::collections::HashMap;

pub struct WikiProxy;

impl WikiProxy {
    /// Generates a beautiful Agent-Native Wiki page in Markdown for a single file.
    pub fn generate_markdown(
        target_path: &str,
        features: &FileFeatures,
        glossary: &Glossary,
    ) -> String {
        let mut wiki = String::new();
        let title = glossary.aliases.get(target_path).unwrap_or(&target_path.to_string()).clone();
        wiki.push_str(&format!("# 📄 {} \n\n", title));
        wiki.push_str(&format!("**物理路徑**: `{}`\n\n", target_path));
        wiki.push_str(&format!("**架構角色**: `{}`\n\n", if features.symbol_count > 10 { "核心樞紐 (HUB)" } else { "葉片節點 (LEAF)" }));
        wiki.push_str("### 🛠️ 語義特徵張量\n");
        wiki.push_str(&format!("*   **邏輯複雜度**: [{}{}] ({:.2})\n", "█".repeat((features.control_flow_score * 5.0) as usize), "░".repeat(5 - (features.control_flow_score * 5.0).min(5.0) as usize), features.control_flow_score));
        wiki.push_str("\n### 🔗 物理符號與出口 (SCIP Exports)\n");
        for sym in &features.exports {
            let sym_alias = glossary.aliases.get(&sym.id).unwrap_or(&sym.name);
            wiki.push_str(&format!("*   `{}` (L{})\n", sym_alias, sym.line));
        }
        wiki.push_str("\n---\n*Generated by CCAP Reverse Proxy | Local Fidelity Verified*");
        wiki
    }

    /// Generates a project-level index with Interactive Vis.js Graph.
    pub fn generate_project_index(
        repo_root: &str,
        results: &[(String, FileFeatures)],
        linker: &Linker,
        glossary: &Glossary,
    ) -> String {
        let mut wiki = String::new();
        let project_name = std::path::Path::new(repo_root).file_name().unwrap_or_default().to_string_lossy().to_string();
        
        wiki.push_str(&format!("# 🌌 專案知識圖譜總覽: {} \n\n", project_name));
        wiki.push_str(&format!("**總掃描檔案數**: `{}`\n\n", results.len()));
        
        wiki.push_str("### 🏗️ 互動式系統架構 (Interactive Topology)\n");
        wiki.push_str("<div id='mynetwork' style='height: 600px; border: 1px solid lightgray; background-color: #fcfcfc; border-radius: 12px;'></div>\n\n");

        // 1. Prepare Nodes and Edges for Vis.js
        let mut nodes_json = String::from("[");
        let mut edges_json = String::from("[");

        let edges = linker.export_edges();
        let paths = linker.get_node_paths();
        
        for (idx, path) in paths.iter().enumerate() {
            let alias = glossary.aliases.get(path).unwrap_or(path);
            let color = if results.iter().any(|(p, f)| p == path && f.symbol_count > 10) { "#AEB98F" } else { "#D3D3D3" };
            nodes_json.push_str(&format!("{{ \"id\": {}, \"label\": \"{}\", \"color\": \"{}\" }},", idx, alias, color));
        }
        for (u, v, _) in edges.iter().take(200) { // Limit for browser performance
            edges_json.push_str(&format!("{{ \"from\": {}, \"to\": {}, \"arrows\": \"to\" }},", u, v));
        }
        nodes_json.push_str("]");
        edges_json.push_str("]");

        wiki.push_str(&format!("<script>const graphData = {{ nodes: {}, edges: {} }};</script>\n", nodes_json, edges_json));

        wiki.push_str("### 🏢 戰略語義分區 (Semantic Rooms)\n\n");
        let mut sym_data = HashMap::new();
        for (path, features) in results {
            sym_data.insert(path.clone(), features.top_symbols.clone());
        }

        let k_rooms = 3.max(results.len() / 50).min(8);
        if let Ok(clusters) = MathEngine::spectral_cluster(&paths, &edges, k_rooms, &sym_data) {
             for cluster in clusters {
                if cluster.members.is_empty() { continue; }
                wiki.push_str(&format!("#### 📌 區域: `{}`\n", cluster.name));
                let mut room_files: Vec<_> = results.iter().filter(|(p, _)| cluster.members.contains(p)).collect();
                room_files.sort_by(|a, b| b.1.control_flow_score.partial_cmp(&a.1.control_flow_score).unwrap());
                for (p, feat) in room_files.iter().take(5) {
                    let alias = glossary.aliases.get(p).unwrap_or(p);
                    wiki.push_str(&format!("*   **{}** - 複雜度: `{:.2}`\n", alias, feat.control_flow_score));
                }
                wiki.push_str("\n");
            }
        }
        wiki.push_str("\n---\n*Generated by CCAP Reverse Proxy | Local Fidelity Verified*");
        wiki
    }

    fn parse_inline_markdown(text: &str) -> String {
        let mut html = text.to_string();
        while let Some(start) = html.find('`') {
            if let Some(end) = html[start + 1..].find('`') {
                let end_idx = start + 1 + end;
                html = format!("{}<code>{}</code>{}", &html[..start], &html[start+1..end_idx], &html[end_idx+1..]);
            } else { break; }
        }
        while let Some(start) = html.find("**") {
            if let Some(end) = html[start + 2..].find("**") {
                let end_idx = start + 2 + end;
                html = format!("{}<strong>{}</strong>{}", &html[..start], &html[start+2..end_idx], &html[end_idx+2..]);
            } else { break; }
        }
        html
    }

    pub fn generate_html(markdown_content: &str) -> String {
        let mut wiki_html = String::new();
        let mut script_buffer = String::new();
        let mut in_script = false;

        for line in markdown_content.lines() {
            let trimmed = line.trim();
            if trimmed.is_empty() { continue; }
            
            if trimmed.starts_with("<script>") {
                in_script = true;
                continue;
            } else if trimmed == "</script>" {
                in_script = false;
                continue;
            }
            if in_script {
                script_buffer.push_str(&format!("{}\n", trimmed));
                continue;
            }

            if trimmed.starts_with("<div") {
                wiki_html.push_str(trimmed);
                continue;
            }

            if trimmed.starts_with("# ") {
                wiki_html.push_str(&format!("<h1>{}</h1>", Self::parse_inline_markdown(&trimmed[2..])));
            } else if trimmed.starts_with("### ") {
                wiki_html.push_str(&format!("<h3>{}</h3>", Self::parse_inline_markdown(&trimmed[4..])));
            } else if trimmed.starts_with("#### ") {
                wiki_html.push_str(&format!("<h4>{}</h4>", Self::parse_inline_markdown(&trimmed[5..])));
            } else if trimmed.starts_with("* ") {
                wiki_html.push_str(&format!("<li>{}</li>", Self::parse_inline_markdown(&trimmed[2..])));
            } else {
                wiki_html.push_str(&format!("<p>{}</p>", Self::parse_inline_markdown(trimmed)));
            }
        }

        format!(r#"
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>CCAP Architectural Dashboard</title>
    <script type="text/javascript" src="https://unpkg.com/vis-network/standalone/umd/vis-network.min.js"></script>
    <style>
        body {{ font-family: 'Segoe UI', Tahoma, sans-serif; line-height: 1.6; color: #333; max-width: 1100px; margin: 40px auto; padding: 20px; background-color: #f0f2f5; }}
        #content {{ background: white; padding: 50px; border-radius: 16px; box-shadow: 0 10px 30px rgba(0,0,0,0.1); border-top: 10px solid #AEB98F; }}
        h1 {{ color: #1a2a3a; font-size: 2.2em; margin-bottom: 30px; text-align: center; }}
        h3 {{ color: #2c3e50; border-left: 5px solid #AEB98F; padding-left: 15px; margin-top: 40px; }}
        h4 {{ color: #556b2f; margin-top: 20px; background: #f9fbf2; padding: 8px; border-radius: 4px; }}
        li {{ background: #fff; margin: 8px 0; padding: 12px; border: 1px solid #eee; border-radius: 8px; transition: 0.3s; list-style: none; }}
        li:hover {{ transform: translateX(5px); border-color: #AEB98F; }}
        code {{ background: #eee; padding: 2px 5px; border-radius: 4px; color: #d63384; font-family: 'Consolas', monospace; }}
        .footer {{ margin-top: 50px; text-align: center; color: #999; font-size: 0.9em; }}
    </style>
</head>
<body>
    <div id="content">{}</div>
    <div class="footer">CCAP V6.0 Gold | The Semantic Operating System</div>
    <script type="text/javascript">
        {}
        const container = document.getElementById('mynetwork');
        const options = {{
            nodes: {{ shape: 'dot', size: 16, font: {{ size: 12, color: '#000' }}, borderWidth: 2 }},
            edges: {{ width: 2, color: {{ inherit: 'from' }}, smooth: {{ type: 'continuous' }} }},
            physics: {{ stabilization: true, barnesHut: {{ gravitationalConstant: -2000, centralGravity: 0.3, springLength: 95 }} }},
            interaction: {{ dragNodes: true, zoomView: true, dragView: true }}
        }};
        const network = new vis.Network(container, graphData, options);
    </script>
</body>
</html>
        "#, wiki_html, script_buffer)
    }
}
