use crate::engine::{extractor::FileFeatures, glossary::Glossary};

pub struct WikiProxy;

impl WikiProxy {
    /// Generates a精美 (beautiful) Agent-Native Wiki page for a given room or file.
    pub fn generate_page(
        _repo_root: &str,
        target_path: &str,
        features: &FileFeatures,
        glossary: &Glossary,
    ) -> String {
        let mut wiki = String::new();
        
        let title = glossary.aliases.get(target_path)
            .unwrap_or(&target_path.to_string())
            .clone();

        wiki.push_str(&format!("# 📄 {} \n\n", title));
        wiki.push_str(&format!("**物理路徑**: `{}`\n", target_path));
        wiki.push_str(&format!("**架構角色**: `{}`\n", if features.symbol_count > 10 { "核心樞紐 (HUB)" } else { "葉片節點 (LEAF)" }));
        
        wiki.push_str("\n### 🛠️ 語義特徵張量\n");
        wiki.push_str(&format!("*   **邏輯複雜度**: [{}{}] ({:.2})\n", 
            "█".repeat((features.control_flow_score * 5.0) as usize),
            "░".repeat(5 - (features.control_flow_score * 5.0).min(5.0) as usize),
            features.control_flow_score
        ));
        wiki.push_str(&format!("*   **數據密度**:   [{}{}] ({:.2})\n", 
            "█".repeat((features.data_density_score * 5.0) as usize),
            "░".repeat(5 - (features.data_density_score * 5.0).min(5.0) as usize),
            features.data_density_score
        ));

        wiki.push_str("\n### 🔗 物理符號與出口 (SCIP Exports)\n");
        for sym in &features.exports {
            let sym_alias = glossary.aliases.get(&sym.id).unwrap_or(&sym.name);
            wiki.push_str(&format!("*   `{}` (L{})\n", sym_alias, sym.line));
        }

        wiki.push_str("\n---\n*Generated by CCAP Reverse Proxy | Local Fidelity Verified*");
        
        wiki
    }
}
